### ISSUE TITLE
Roadmap Suggestion

### ISSUE THREAD

**Issue by jus0xA** [iknowjason/PurpleCloud#18]
Really enjoying PurpleCloud! Amazing work! On a side note, I just wanted to make a suggestion for the [roadmap](https://www.purplecloud.network/future/) of creating an Azure Web App for Containers setup with a  [Juice Shop](https://owasp.org/www-project-juice-shop/) deployment.

**Comment by iknowjason** [comment]
@jus0xA 

That's a great idea.  I've added it to the roadmap.
