### ISSUE TITLE
PurpleSharp is not available inside the tools directory

### ISSUE THREAD

**Issue by RahulIngenious** [iknowjason/PurpleCloud#31]
Hi @iknowjason ,

as per the lab (_Microsoft Sentinel lab with AD, deployed with terraform. Adds logging best practices with Sysmon_.) demonstration PurpleSharp tool is supposed to be available in the tools directory of the host. However, when i ran the query or checked it manually i couldn't find any. Could you please look into this?

Also, i would like to know once this issue is resolved. After running this PrupleSharp adversary emulation tool. Would i be able to see the alerts in Defender for endpoint for the same? 
PS: I have installed Defender for Endpoint on both hosts.

![PurpleSharp](https://github.com/iknowjason/PurpleCloud/assets/153918394/3ebe10f4-a74e-48c3-b47d-baaf05d7cae5)

**Comment by iknowjason** [comment]
Hi @RahulIngenious 

Yes, I will look into this and help get it resolved for you.  It might be that the PurpleSharp download link has changed.  I will verify.

What do you mean by, ```as per the lab (Microsoft Sentinel lab with AD, deployed with terraform```?  You mean the generator python script that creates this lab scenario?  Or something outside of PurpleCloud tool?

Jason

**Comment by RahulIngenious** [comment]
@iknowjason - Yes, the generator python script that creates this lab scenario

**Comment by iknowjason** [comment]
@RahulIngenious 

I just tested on a new lab and PurpleSharp downloads.  In your case it could have been any kind of issue like a temporary networking issue.  I"m attaching three images of what you can check on your end.

Why don't you just download PurpleSharp onto your system since it apparently didn't download?  The bootstrap script shows the command.  I will copy and paste it here.  Open up a powershell admin session and type this:
```

**Comment by iknowjason** [comment]
@RahulIngenious 

After you run PurpleSharp it should be able to generate alerts.  As for Windows Defender endpoint, I can't troubleshoot your system on that.

**Comment by iknowjason** [comment]
@RahulIngenious Do you still need help here?  I'm going to close this out.  But feel free to re-open if you still need help.
