### ISSUE TITLE
Path to Atomic Red Team needs to be updated

### ISSUE THREAD

**Issue by akn0w** [iknowjason/PurpleCloud#6]
Download path needs to be updated to current path of Atomic Red Team.

New Path: https://github.com/redcanaryco/atomic-red-team/archive/refs/heads/master.zip

Old Path: https://github.com/redcanaryco/atomic-red-team/archive/master.zip

bluetools: PurpleCloud-master\modules\win10-vm\roles\art\files
bluetools: PurpleCloud-master\modules\win10-vm\roles\endpoint\files

**Comment by iknowjason** [comment]
Thanks.  Will check this out and get it updated soon.

**Comment by akn0w** [comment]
@iknowjason - I have some more detailed instructions if you're interested as well.

**Comment by iknowjason** [comment]
Verified the issue and you are correct @akn0w .  I've made changes to bluetools.ps1 to update the path to Atomic Red Team and pushed to origin master.  Thanks!  Closing the issue.
