### ISSUE TITLE
Issue with deplying helk

### ISSUE THREAD

**Issue by mateusz-sobczak** [iknowjason/PurpleCloud#8]
The azure.py file uses wrong variable in "os_disk" method (line 1621), it should be:
name = "${local.virtual_machine_name_helk}-disk1"

current value:
name = "${local.virtual_machine_name}-disk1"

(Or "name" parameter should be removed?? like for endpoint & DC)

**Comment by iknowjason** [comment]
@mateusz-sobczak 

Thanks for the heads up.  I'm taking a look at this and will verify ASAP.

**Comment by iknowjason** [comment]
Hello @mateusz-sobczak 

I've confirmed that you are correct.  Very nice catch.  Thank you.  This issue has been resolved in latest commit.
